# Generated by Django 3.0.4 on 2020-03-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('markers', models.FileField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
